version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      my_network:
        ipv4_address: 172.18.0.50

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.18.0.0/24